import { NagPackSuppression } from 'cdk-nag';

/**
 * cdk-nag suppressions for the VoC Data Lake project
 * Add suppressions here as we review and approve them
 */

// CDK Custom Resource Lambdas (managed by CDK, not our code)
export const cdkCustomResourceSuppressions: NagPackSuppression[] = [
  {
    id: 'AwsSolutions-L1',
    reason: 'CDK-managed custom resource Lambda functions use CDK-controlled runtimes',
  },
];

// DynamoDB PITR for idempotency table
export const idempotencyTableSuppressions: NagPackSuppression[] = [
  {
    id: 'AwsSolutions-DDB3',
    reason: 'Idempotency table has 15-minute TTL - transient data does not require point-in-time recovery',
  },
];

// S3 access logging for CloudFront-fronted buckets
export const websiteBucketSuppressions: NagPackSuppression[] = [
  {
    id: 'AwsSolutions-S1',
    reason: 'Website bucket is served exclusively through CloudFront - CloudFront access logs provide traffic visibility',
  },
];

// AWSLambdaBasicExecutionRole - AWS managed policy for Lambda CloudWatch logging
export const lambdaBasicExecutionRoleSuppressions: NagPackSuppression[] = [
  {
    id: 'AwsSolutions-IAM4',
    reason: 'AWSLambdaBasicExecutionRole is AWS-recommended managed policy for Lambda CloudWatch logging with minimal permissions',
    appliesTo: ['Policy::arn:<AWS::Partition>:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole'],
  },
];

// CloudFront distributions using default certificate
export const cloudfrontDefaultCertSuppressions: NagPackSuppression[] = [
  {
    id: 'AwsSolutions-CFR1',
    reason: 'Geo restrictions not required for sample application - can be enabled based on specific compliance requirements',
  },
  {
    id: 'AwsSolutions-CFR2',
    reason: 'AWS WAF not included to minimize costs for sample deployment - recommended for production use',
  },
  {
    id: 'AwsSolutions-CFR4',
    reason: 'CloudFront distributions using default certificate (*.cloudfront.net) are limited to TLSv1 by AWS - custom domain with ACM certificate required for TLSv1.2+. See: https://docs.aws.amazon.com/AWSCloudFormation/latest/TemplateReference/aws-properties-cloudfront-distribution-viewercertificate.html#cfn-cloudfront-distribution-viewercertificate-minimumprotocolversion',
  },
];

// Cognito User Pool security settings
export const cognitoSecuritySuppressions: NagPackSuppression[] = [
  {
    id: 'AwsSolutions-COG2',
    reason: 'MFA not enforced by default to reduce friction for sample application - users can enable MFA in their account settings',
  },
  {
    id: 'AwsSolutions-COG3',
    reason: 'Cognito Advanced Security Mode not enforced to minimize costs for sample deployment ($0.05 per login attempt) - recommended for production use',
  },
];

// Secrets Manager rotation for API credentials
export const apiSecretsSuppressions: NagPackSuppression[] = [
  {
    id: 'AwsSolutions-SMG4',
    reason: 'Secret contains third-party API credentials that cannot be automatically rotated by AWS - requires manual rotation through provider portals',
  },
];

// DynamoDB Global Secondary Index access
export const dynamoDbGsiSuppressions: NagPackSuppression[] = [
  {
    id: 'AwsSolutions-IAM5',
    reason: 'Wildcard required for DynamoDB Global Secondary Index access - GSI ARNs follow pattern <TableArn>/index/* per AWS best practices',
    appliesTo: [
      'Resource::<FeedbackTableF528636C.Arn>/index/*',
      'Resource::<AggregatesTable0F8EFB12.Arn>/index/*',
      'Resource::<ProjectsTableAA0A2089.Arn>/index/*',
      'Resource::<JobsTable1970BC16.Arn>/index/*',
    ],
  },
];

// KMS encryption operations - CDK grantEncryptDecrypt() uses wildcards
export const kmsEncryptionSuppressions: NagPackSuppression[] = [
  {
    id: 'AwsSolutions-IAM5',
    reason: 'KMS wildcard actions (GenerateDataKey*, ReEncrypt*) are generated by CDK grantEncryptDecrypt() construct - covers multiple related encryption operations',
    appliesTo: [
      'Action::kms:GenerateDataKey*',
      'Action::kms:ReEncrypt*',
    ],
  },
];

// S3 bucket operations - CDK grantReadWrite() and grantRead() use wildcards
export const s3BucketSuppressions: NagPackSuppression[] = [
  {
    id: 'AwsSolutions-IAM5',
    reason: 'S3 wildcard actions are generated by CDK bucket grant methods (grantReadWrite, grantRead) - covers related S3 operations',
    appliesTo: [
      'Action::s3:Abort*',
      'Action::s3:DeleteObject*',
      'Action::s3:GetBucket*',
      'Action::s3:GetObject*',
      'Action::s3:List*',
    ],
  },
  {
    id: 'AwsSolutions-IAM5',
    reason: 'S3 object access requires wildcard on bucket ARN (bucket-arn/*) - AWS best practice for object-level permissions',
    appliesTo: [
      'Resource::<RawDataBucket57F26C03.Arn>/*',
      'Resource::<S3ImportBucket676867E6.Arn>/*',
      'Resource::<WebsiteBucket75C24D94.Arn>/*',
      'Resource::<RawDataBucket57F26C03.Arn>/avatars/*',
    ],
  },
];

// Bedrock foundation model ARNs - region wildcard required
export const bedrockModelSuppressions: NagPackSuppression[] = [
  {
    id: 'AwsSolutions-IAM5',
    reason: 'Bedrock foundation model ARNs require region wildcard as models are cross-region resources',
    appliesTo: [
      'Resource::arn:aws:bedrock:*::foundation-model/anthropic.claude-sonnet-4-5-20250929-v1:0',
      'Resource::arn:aws:bedrock:*::foundation-model/anthropic.claude-haiku-4-5-20251001-v1:0',
    ],
  },
];

// Dynamic plugin system - Lambda and EventBridge wildcards
export const pluginSystemSuppressions: NagPackSuppression[] = [
  {
    id: 'AwsSolutions-IAM5',
    reason: 'Plugin system requires wildcards for dynamic Lambda function names and EventBridge rules created at runtime',
    appliesTo: [
      'Resource::arn:aws:lambda:us-east-1:<AWS::AccountId>:function:voc-ingestor-webscraper-*',
      'Resource::arn:aws:lambda:us-east-1:<AWS::AccountId>:function:voc-manual-import-processor-*',
      'Resource::arn:aws:lambda:us-east-1:<AWS::AccountId>:function:voc-projects-api-*',
      'Resource::arn:aws:events:us-east-1:<AWS::AccountId>:rule/voc-ingest-*-schedule',
    ],
  },
  {
    id: 'AwsSolutions-IAM5',
    reason: 'Lambda version/alias wildcard required for function invocations',
    appliesTo: [
      'Resource::<ResearchStepLambdaDB89028D.Arn>:*',
      'Resource::<ModelAgreementLambda98DD007E.Arn>:*',
    ],
  },
];

// CDK deployment assets
export const cdkAssetsSuppressions: NagPackSuppression[] = [
  {
    id: 'AwsSolutions-IAM5',
    reason: 'CDK bootstrap bucket wildcard required for deployment assets',
    appliesTo: [
      'Resource::arn:aws:s3:::cdk-hnb659fds-assets-<AWS::AccountId>-us-east-1/*',
    ],
  },
];

// AWS Comprehend - real-time text analysis APIs
export const comprehendSuppressions: NagPackSuppression[] = [
  {
    id: 'AwsSolutions-IAM5',
    reason: 'Comprehend real-time detection APIs (DetectSentiment, DetectKeyPhrases, DetectDominantLanguage) do not support resource-level permissions - these are stateless analysis operations that require Resource:*',
    appliesTo: [
      'Resource::*',
    ],
  },
];

// AWS Translate - real-time translation API
export const translateSuppressions: NagPackSuppression[] = [
  {
    id: 'AwsSolutions-IAM5',
    reason: 'Translate TranslateText API requires Resource:* for real-time translation without custom parallel data - parallel data ARNs only apply when using custom terminology/translation memories',
    appliesTo: [
      'Resource::*',
    ],
  },
];

// API Gateway request validation
export const apiGatewayRequestValidationSuppressions: NagPackSuppression[] = [
  {
    id: 'AwsSolutions-APIG2',
    reason: 'Request validation handled by Lambda functions with comprehensive input validation using Pydantic models and custom logic',
  },
  {
    id: 'AwsSolutions-APIG3',
    reason: 'AWS WAF not included to minimize costs for sample deployment - recommended for production use',
  },
];

// Public feedback form endpoints (intentionally unauthenticated)
export const publicFeedbackEndpointSuppressions: NagPackSuppression[] = [
  {
    id: 'AwsSolutions-APIG4',
    reason: 'Feedback form endpoints are intentionally public to allow anonymous customer feedback submission',
  },
  {
    id: 'AwsSolutions-COG4',
    reason: 'Feedback form endpoints are intentionally public to allow anonymous customer feedback submission - Cognito authentication would prevent external users from submitting feedback',
  },
];
