/**
 * The point of these tests is CROSS-LANGUAGE AGREEMENT.
 *
 * Avatar URLs are signed by two implementations — this one and
 * `lambda/shared/cloudfront_signing.py` — and CloudFront verifies the signature
 * against the exact policy bytes. A difference as small as one space, or a
 * different key order, yields a signature CloudFront rejects, and the failure
 * would surface only as a 403 in a browser after deploying.
 *
 * The guarantee is assembled from three parts rather than by pinning a signed
 * URL against a committed key, because that would mean checking a real
 * `-----BEGIN PRIVATE KEY-----` into a public repository:
 *
 *   1. the canned policy bytes match botocore exactly (fixture generated by
 *      `.tmp/gen_signing_fixture.py` from CloudFrontSigner.build_policy);
 *   2. the signature this module produces verifies against the matching public
 *      key under RSA-SHA1 / PKCS#1 v1.5 — the exact check CloudFront performs;
 *   3. the query parameters are named, ordered and encoded as CloudFront wants.
 *
 * RSA PKCS#1 v1.5 is deterministic, so 1 + 2 together imply both
 * implementations emit identical signatures for identical keys.
 */
import { describe, it, expect, beforeEach, afterEach } from 'vitest';
import { createVerify, generateKeyPairSync } from 'node:crypto';
import fixture from './__fixtures__/cloudfront-signing.botocore.json';
import {
  buildCannedPolicy,
  buildSignedUrl,
  clearSigningCache,
  signUrlWithKey,
} from './cloudfront-signing.js';

/** Matches what the cdn_signing_keys custom resource generates at deploy time. */
function testKeyPair() {
  return generateKeyPairSync('rsa', {
    modulusLength: 2048,
    publicKeyEncoding: { type: 'spki', format: 'pem' },
    privateKeyEncoding: { type: 'pkcs8', format: 'pem' },
  });
}

/** Undo CloudFront's base64 variant. */
function decodeSignature(signature: string): Buffer {
  return Buffer.from(
    signature.replaceAll('-', '+').replaceAll('_', '=').replaceAll('~', '/'),
    'base64',
  );
}

describe('canned policy serialization', () => {
  it('matches botocore byte-for-byte', () => {
    expect(buildCannedPolicy(fixture.url, fixture.expiresEpochSeconds)).toBe(
      fixture.expectedCannedPolicy,
    );
  });

  it('matches botocore for a url that already has a query string', () => {
    expect(buildCannedPolicy(fixture.urlWithQuery, fixture.expiresEpochSeconds)).toBe(
      fixture.expectedCannedPolicyForUrlWithQuery,
    );
  });

  it('emits no whitespace padding', () => {
    // botocore uses separators=(',',':'). JSON.stringify agrees today; pinning
    // it means a future "pretty-print for debugging" edit fails here rather than
    // silently at the edge.
    expect(buildCannedPolicy('https://x/y', 1)).not.toContain(' ');
  });

  it('puts Resource before Condition, which is significant for a canned policy', () => {
    const policy = buildCannedPolicy(fixture.url, fixture.expiresEpochSeconds);
    expect(policy.indexOf('"Resource"')).toBeLessThan(policy.indexOf('"Condition"'));
  });
});

describe('signUrlWithKey', () => {
  it('produces a signature CloudFront would accept, i.e. RSA-SHA1 over the policy', () => {
    const { publicKey, privateKey } = testKeyPair();

    const signed = signUrlWithKey(
      fixture.url,
      privateKey,
      fixture.keyPairId,
      fixture.expiresEpochSeconds,
    );

    const signature = new URL(signed).searchParams.get('Signature') ?? '';
    const verified = createVerify('RSA-SHA1')
      .update(fixture.expectedCannedPolicy)
      .verify(publicKey, decodeSignature(signature));

    // Verifying against the BOTOCORE policy string, not our own — so this fails
    // if the two implementations ever sign different bytes.
    expect(verified).toBe(true);
  });

  it('is deterministic for the same key, url and expiry', () => {
    // PKCS#1 v1.5 has no random salt. This is what lets parts 1 and 2 above add
    // up to byte-identical output across the two languages.
    const { privateKey } = testKeyPair();
    const once = signUrlWithKey(fixture.url, privateKey, 'KID', 123);
    const twice = signUrlWithKey(fixture.url, privateKey, 'KID', 123);

    expect(once).toBe(twice);
  });

  it('uses the CloudFront base64 alphabet, not standard base64', () => {
    const { privateKey } = testKeyPair();
    const signed = signUrlWithKey(fixture.url, privateKey, fixture.keyPairId, 123);
    const signature = new URL(signed).searchParams.get('Signature') ?? '';

    // CloudFront maps + / = onto - ~ _ ; any original reaching the wire means a
    // mangled or rejected URL.
    expect(signature).not.toMatch(/[+/=]/);
    expect(signature.length).toBeGreaterThan(0);
  });
});

describe('buildSignedUrl', () => {
  it('starts a query string when the URL has none', () => {
    const out = buildSignedUrl('https://d1.cloudfront.net/a.jpeg', 42, Buffer.from('sig'), 'KID');
    expect(out).toContain('/a.jpeg?Expires=42');
  });

  it('appends to an existing query string instead of starting a second one', () => {
    const out = buildSignedUrl('https://d1.cloudfront.net/a.jpeg?v=2', 42, Buffer.from('sig'), 'KID');
    expect(out).toContain('?v=2&Expires=42');
    expect(out.match(/\?/g)).toHaveLength(1);
  });

  it('orders the parameters Expires, Signature, Key-Pair-Id', () => {
    const out = buildSignedUrl('https://d1.cloudfront.net/a.jpeg', 42, Buffer.from('sig'), 'KID');
    expect(out.indexOf('Expires=')).toBeLessThan(out.indexOf('Signature='));
    expect(out.indexOf('Signature=')).toBeLessThan(out.indexOf('Key-Pair-Id='));
  });
});

describe('signCloudFrontUrl fail-closed behavior', () => {
  const saved = { ...process.env };

  beforeEach(() => {
    clearSigningCache();
    delete process.env.CDN_SIGNING_SECRET_ARN;
    delete process.env.CDN_SIGNING_KEY_PAIR_ID;
  });

  afterEach(() => {
    process.env = { ...saved };
    clearSigningCache();
  });

  it('returns undefined when signing is not configured', async () => {
    // Never a bare URL: /avatars/* requires a signature, and emitting the
    // unsigned form would be handing out an unauthenticated link.
    const { signCloudFrontUrl } = await import('./cloudfront-signing.js');
    await expect(signCloudFrontUrl('https://d1.cloudfront.net/avatars/a.jpeg')).resolves.toBeUndefined();
  });

  it('returns undefined when only the key pair id is configured', async () => {
    process.env.CDN_SIGNING_KEY_PAIR_ID = 'KID';
    const { signCloudFrontUrl } = await import('./cloudfront-signing.js');
    await expect(signCloudFrontUrl('https://d1.cloudfront.net/avatars/a.jpeg')).resolves.toBeUndefined();
  });

  it('returns undefined for an empty url even when configured', async () => {
    process.env.CDN_SIGNING_SECRET_ARN = 'arn:aws:secretsmanager:us-east-1:1:secret:x';
    process.env.CDN_SIGNING_KEY_PAIR_ID = 'KID';
    const { signCloudFrontUrl } = await import('./cloudfront-signing.js');
    await expect(signCloudFrontUrl('')).resolves.toBeUndefined();
  });
});
