/**
 * CloudFront signed-URL minting for the private `/avatars/*` cache behavior
 * (issue #229).
 *
 * WHY THIS EXISTS IN TYPESCRIPT TOO
 * This Lambda emits persona avatar URLs in the `persona_turn` SSE event, which
 * the SPA renders with `<img src>` (frontend ChatBubbles.tsx). Once
 * `/avatars/*` requires a signature, an unsigned URL from here would 403 and
 * project-chat avatars would silently break — so the Python signer in
 * `lambda/shared/cloudfront_signing.py` is not sufficient on its own.
 *
 * DELIBERATE PORT, kept byte-compatible with that module: both produce the
 * CANNED policy that `botocore.signers.CloudFrontSigner` produces, so the two
 * implementations cannot drift into signing different things. If you change one,
 * change the other — `cloudfront-signing.test.ts` pins the wire format against
 * a fixture generated by botocore.
 *
 * No dependency needed: Node's `crypto` does RSA-SHA1 natively, which is the
 * only algorithm CloudFront accepts here (and the reason `kms:Sign`, which has
 * no SHA-1 option, cannot be used).
 *
 * FAILS CLOSED, like the Python side: no signing config means `undefined`, never
 * a bare URL.
 */
import { createSign } from 'node:crypto';
import { GetSecretValueCommand, SecretsManagerClient } from '@aws-sdk/client-secrets-manager';

/** See FALLBACK_TTL_SECONDS in shared/cloudfront_signing.py. */
const FALLBACK_TTL_SECONDS = 3600;

/**
 * CloudFront's base64 variant for signature and policy parameters: the standard
 * alphabet produces characters that are not URL-safe.
 */
function urlSafeBase64(buffer: Buffer): string {
  return buffer.toString('base64').replaceAll('+', '-').replaceAll('=', '_').replaceAll('/', '~');
}

/**
 * The canned policy, serialized exactly as botocore does it: key order
 * Resource-then-Condition, and no whitespace between tokens. CloudFront
 * verifies the signature against these bytes, so the serialization is part of
 * the wire contract, not a formatting choice.
 */
export function buildCannedPolicy(url: string, expiresEpochSeconds: number): string {
  return JSON.stringify({
    Statement: [{ Resource: url, Condition: { DateLessThan: { 'AWS:EpochTime': expiresEpochSeconds } } }],
  });
}

/** Append the signature parameters, preserving any query string already present. */
export function buildSignedUrl(
  url: string,
  expiresEpochSeconds: number,
  signature: Buffer,
  keyPairId: string,
): string {
  const separator = url.includes('?') ? '&' : '?';
  const params = [
    `Expires=${expiresEpochSeconds}`,
    `Signature=${urlSafeBase64(signature)}`,
    `Key-Pair-Id=${keyPairId}`,
  ];
  return `${url}${separator}${params.join('&')}`;
}

export function signUrlWithKey(
  url: string,
  privateKeyPem: string,
  keyPairId: string,
  expiresEpochSeconds: number,
): string {
  const policy = buildCannedPolicy(url, expiresEpochSeconds);
  const signature = createSign('RSA-SHA1').update(policy).sign(privateKeyPem);
  return buildSignedUrl(url, expiresEpochSeconds, signature, keyPairId);
}

const secretsClient = new SecretsManagerClient({});

/**
 * Cached per container: the secret fetch is a network call and the PEM never
 * changes for the life of the container. A Map rather than a reassigned
 * variable because the lint config bans `let` outright — inserting into a
 * `const` Map is the sanctioned way to hold mutable state here.
 */
const privateKeyPemCache = new Map<string, string>();

/** Narrow parsed JSON without an `as` assertion. */
function isRecord(value: unknown): value is Record<string, unknown> {
  return typeof value === 'object' && value !== null && !Array.isArray(value);
}

/** The secret holds {privateKeyPem, publicKeyPem}; only the private half is needed here. */
function extractPrivateKeyPem(secretString: string): string | undefined {
  const parsed: unknown = JSON.parse(secretString);
  if (!isRecord(parsed)) return undefined;
  const pem = parsed.privateKeyPem;
  // A secret can legitimately exist without a key: CDK seeds it with a random
  // password before the bootstrap custom resource populates it.
  if (typeof pem !== 'string' || !pem.includes('PRIVATE KEY')) return undefined;
  return pem;
}

async function loadPrivateKeyPem(secretArn: string): Promise<string | undefined> {
  const cached = privateKeyPemCache.get(secretArn);
  if (cached !== undefined) return cached;
  try {
    const out = await secretsClient.send(new GetSecretValueCommand({ SecretId: secretArn }));
    if (!out.SecretString) {
      console.warn('cloudfront-signing: signing secret has no SecretString; avatars will be omitted');
      return undefined;
    }
    const pem = extractPrivateKeyPem(out.SecretString);
    if (pem === undefined) {
      console.warn('cloudfront-signing: signing secret holds no usable privateKeyPem; avatars will be omitted');
      return undefined;
    }
    privateKeyPemCache.set(secretArn, pem);
    return pem;
  } catch (error) {
    // Failing closed is correct, but silence is not: an IAM denial or a missing
    // secret otherwise shows up only as avatars quietly vanishing from
    // persona_turn, with nothing to grep for. Name is enough — never log the
    // secret payload.
    console.warn(
      `cloudfront-signing: could not read the signing secret (${error instanceof Error ? error.name : 'unknown'}); avatars will be omitted`,
    );
    return undefined;
  }
}

/** Test seam: drop the cached PEM. */
export function clearSigningCache(): void {
  privateKeyPemCache.clear();
}

function ttlSeconds(): number {
  const parsed = Number.parseInt(process.env.CDN_SIGNED_URL_TTL_SECONDS ?? '', 10);
  return Number.isFinite(parsed) && parsed > 0 ? parsed : FALLBACK_TTL_SECONDS;
}

/**
 * Sign an absolute distribution URL, or return undefined when it cannot be
 * signed. Undefined means "emit no avatar" — the SPA already falls back to a
 * gradient avatar — and never means "send the unsigned URL".
 */
export async function signCloudFrontUrl(url: string): Promise<string | undefined> {
  const secretArn = process.env.CDN_SIGNING_SECRET_ARN ?? '';
  const keyPairId = process.env.CDN_SIGNING_KEY_PAIR_ID ?? '';
  if (!url) return undefined;
  if (!secretArn || !keyPairId) {
    console.warn(
      'cloudfront-signing: CDN_SIGNING_SECRET_ARN/CDN_SIGNING_KEY_PAIR_ID not set; '
      + 'refusing to emit an unsigned URL for a private CDN path',
    );
    return undefined;
  }

  const privateKeyPem = await loadPrivateKeyPem(secretArn);
  if (!privateKeyPem) return undefined;

  const expires = Math.floor(Date.now() / 1000) + ttlSeconds();
  try {
    return signUrlWithKey(url, privateKeyPem, keyPairId, expires);
  } catch (error) {
    // A malformed PEM lands here. Same reasoning as above: fail closed, but say so.
    console.warn(
      `cloudfront-signing: signing failed (${error instanceof Error ? error.name : 'unknown'}); avatar will be omitted`,
    );
    return undefined;
  }
}
