blank_issues_enabled: false
contact_links:
  - name: Documentation
    url: https://github.com/aws-samples/sample-voice-of-customer-datalake/tree/main/docs
    about: Check the documentation before opening an issue
